alias mktar="tar -cvf "
alias untar="tar -xvf "
alias mktargz="tar -cvzf "
alias untargz="tar -xvzf "
alias find-file="find . -name "
alias find-dir="find . -type d -name "
alias find-text="grep -rInH "
