alias mktar="tar -cvf "
alias untar="tar -xvf "
alias mktargz="tar -cvzf "
alias untargz="tar -xvzf "
alias find-file="find . -name "
alias find-dir="find . -type d -name "
alias find-text="grep -rIinH "
alias files-count="ls | wc -l"

youtube_downloader_dir="/opt/youtube-downloader"
youtube_downloader_file="youtube-dl"
alias youtube-downloader-get="sudo mkdir -p $youtube_downloader_dir && sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o $youtube_downloader_dir/$youtube_downloader_file"
alias youtube-downloader-remove="sudo rm $youtube_downloader_dir/$youtube_downloader_file"
alias youtube-downloader-help="python $youtube_downloader_dir/$youtube_downloader_file --help"
alias youtube-downloader-formats="python $youtube_downloader_dir/$youtube_downloader_file -F "
alias youtube-downloader-download="python $youtube_downloader_dir/$youtube_downloader_file -f "
